### ISSUE TITLE
Что это?

### ISSUE THREAD

**Issue by ffdown** [lo-th/Comfyui_three_js#11]
Хоть бы какой то гайд, что это и зачем? а то делаешь обновляешь, а нафиг это надо и как этим пользоваться ни строчки =)

**Comment by lo-th** [comment]
все есть в названии ;)
на данный момент это экспериментально
это переход от 3D-модели к изображению AI
ничего делать не нужно, просто запустите рабочий процесс в comfyui

но вы правы немного больше описания.
хотя цель еще предстоит определить

**Comment by ffdown** [comment]
Поставил запустил, ну так и пишем, что натягивание текстур на 3D болванки =)) Правда один нюанс болванка входная в неизвестном мне формате, если бы подгружать можно было что-то вроде obx, blend и прочих распространённых форматов, был бы кайф =)

Да и с сержевой LLM какие-то траблы 
[https://github.com/SeargeDP/ComfyUI_Searge_LLM/issues/23#issuecomment-2522181648](url)

**Comment by lo-th** [comment]
да, я могу добавить другие форматы obj fbx... три js принимают многие
